modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="create_regex_filter"
version="\${version}"
displayName="Create: Regex Filter"
authors="Aether_254"
description='''Adds a Create filter that matches item registry names or item tags with separate regular expressions.'''

[[dependencies.create_regex_filter]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_regex_filter]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_regex_filter]]
modId="create"
type="required"
versionRange="[6.0.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_regex_filter]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="AFTER"
side="BOTH"

