modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="create_copycat_configuration"
version="${version}"
displayName="Create: Copycat Configuration"
authors="Aether_254"
description='''Adds per-block collision, light occlusion, and brightness settings to Create and Copycats+ copycat blocks.'''

[[mixins]]
config="create_copycat_configuration.mixins.json"

[[dependencies.create_copycat_configuration]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_copycat_configuration]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_copycat_configuration]]
modId="create"
type="required"
versionRange="[6.0.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_copycat_configuration]]
modId="copycats"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_copycat_configuration]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="AFTER"
side="BOTH"

